18-04-2022 vladnewfix3
thulsidk1/TerraformVPC pull request #14
Opened 2022-04-18 15:17 UTC by thulsidk1

this is the latest pull request (vladnewfix3)

2022-04-18 15:22 UTC, vladimirmukhin requested changes

2022-04-18 15:22 UTC, vladimirmukhin commented on resources.tf
> +  }
```suggestion
    Name = "${var.environment_tag}-eip-private${count.index}"
  }
```

2022-04-18 15:22 UTC, vladimirmukhin commented on resources.tf
> +  }
```suggestion
    Name = "${var.environment_tag}-eip-public"
  }
```

2022-04-18 15:22 UTC, vladimirmukhin commented on resources.tf
> +    Name = "${var.environment_tag}-rtb_private1${count.index}"
```suggestion
    Name = "${var.environment_tag}-rtb_private${count.index}"
```

2022-04-18 15:22 UTC, vladimirmukhin commented on resources.tf
> +    Name = "${var.environment_tag}-testInstance"
```suggestion
    Name = "${var.environment_tag}-public"
```

2022-04-18 15:22 UTC, vladimirmukhin commented on resources.tf
> +    Name = "${var.environment_tag}-testInstance1"
```suggestion
    Name = "${var.environment_tag}-private"
```

2022-04-18 15:22 UTC, vladimirmukhin commented on variables.tf
> +
```suggestion

```

2022-04-18 15:22 UTC, vladimirmukhin commented on variables.tf
> +
```suggestion

```

2022-04-19 14:19 UTC, closed without merging

2022-04-19 14:20 UTC, thulsidk1 commented
close